Add profile pic upload under about me section
team-45-su-19/team-45-codeu pull request #51
Opened 2019-06-17 09:40 UTC by Jay-kew

Trying a simple implementation of Blobstore to use for profile pic upload as the messages already have the markdown editor. After uploading, you will be shown the picture but is not saved yet, will be working out the logic to save to datastore and displaying on the user page.

May ignore HomeServlet.java and imagelearn.html for now as they are purely for my understanding and reference while I continue the datastore part

2019-06-17 18:13 UTC, BenMQ requested changes

2019-06-17 18:13 UTC, BenMQ commented on src/main/java/com/google/codeu/servlets/FormHandlerServlet.java
> +//  }
remove these?

2019-06-17 18:13 UTC, BenMQ commented on src/main/java/com/google/codeu/servlets/FormHandlerServlet.java
> +@WebServlet("/my-form-handler")
the path and class names are not super descriptive. 

 ImageFormHandler?

2019-06-27 00:23 UTC, BenMQ approved these changes

2019-06-27 00:23 UTC, BenMQ commented on src/main/java/com/google/codeu/servlets/HomeServlet.java
> +@WebServlet("/home")
i imagine this is only testing right now, yea? can we move this to something like /upload  or do you plan to delete this servlet at some point?

2019-06-30 14:13 UTC, Jay-kew commented
Closing this to refer to the most updated [PR#62](https://github.com/team-45-su-19/team-45-codeu/pull/62)

2019-06-30 14:13 UTC, closed without merging