Add some information to the map in aboutus page
team-45-su-19/team-45-codeu pull request #84
Opened 2019-07-21 16:24 UTC by jyx11011

Add name, photo and address to the infoWindow for markers in about us page

2019-07-22 09:47 UTC, Jay-kew requested changes
Hey Yuxin, I think this is good, really gives the map more information! I think you just need to change the indentation to 2 for the `map.css` and it can be merged :)

2019-07-22 11:07 UTC, calebmah approved these changes

2019-07-22 11:07 UTC, calebmah commented on src/main/webapp/js/about-us-map.js
> +  var a = document.createElement('p');
nit: could call this var `address` or something more informative

2019-07-22 11:07 UTC, calebmah commented on src/main/webapp/js/about-us-map.js
> +function createMarker(lat, lng, title, address, url) {
nit: feel like this should be `image_url` or similar since it needs to be a link to an image

2019-07-24 02:47 UTC, calebmah approved these changes

2019-07-26 01:53 UTC, Jay-kew approved these changes
I think a few more indentation problems were raised by hound, I'll approve first but just be careful and resolve them before merging! :)

2019-07-27 08:56 UTC, merged